# generated
name: xmxqxufh5bxnxdc4k
on:
  workflow_dispatch:
    inputs:
      xjpskkuqrmiyuxpqk:
        type: string
        required: true
  workflow_call:
    inputs:
      xjpskkuqrmiyuxpqk:
        type: string
        required: true
permissions: {}
jobs:
  xjln6vglt73ligtvk:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    outputs:
      x3r74esd2t3qivujw: ${{ steps.run.outputs.x3r74esd2t3qivujw }}
      xh7ju4mc3kbj3h3ca: ${{ steps.run.outputs.xh7ju4mc3kbj3h3ca }}
      xrav2lcmeqo7drpuv: ${{ steps.run.outputs.xrav2lcmeqo7drpuv }}
      xxauzfp5l5zzj6o6s: ${{ steps.run.outputs.xxauzfp5l5zzj6o6s }}
      xz7sxqj2lr6xr3cga: ${{ steps.run.outputs.xz7sxqj2lr6xr3cga }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xeyta5i3nv4bkuler: ${{ secrets.xh7m2ldpw5cql5sep }}
          xqenmlrfq62oinaw4: ${{ secrets.xfwywr56poqftmwc3 }}
          xujyswu2qkj4iywg6: ${{ secrets.xi7t32r45js5lgbof }}
          xcgagul6y7tlo65ik: xxggc7hmyueu6h56p
          xyt5k2ne5oqunwic5: x3r74esd2t3qivujw,xh7ju4mc3kbj3h3ca,xrav2lcmeqo7drpuv,xxauzfp5l5zzj6o6s,xz7sxqj2lr6xr3cga
          xjpskkuqrmiyuxpqk: ${{ inputs.xjpskkuqrmiyuxpqk }}
          x565azhqwteiksi2z: ${{ secrets.x72l2e5chadt2wgmr }}
          xqc3kqqftsenfeumg: ${{ secrets.xsemwodlffbmzobxv }}
          xvimkivhx2tqrmzp5: ${{ secrets.xj4q2oe24ul3gocs3 }}
          xmwtti62frqtunvpo: ${{ secrets.xvp3lwebscbhq4np4 }}
        run: ./.github/bin/xmxqxufh5bxnxdc4k
  x3r7ynpbgkydxit4f:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xjln6vglt73ligtvk
    outputs:
      xznk4uicnif7kv3zo: ${{ steps.run.outputs.xznk4uicnif7kv3zo }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xeyta5i3nv4bkuler: ${{ secrets.xh7m2ldpw5cql5sep }}
          xqenmlrfq62oinaw4: ${{ secrets.xfwywr56poqftmwc3 }}
          xujyswu2qkj4iywg6: ${{ secrets.xi7t32r45js5lgbof }}
          xcgagul6y7tlo65ik: xgeztzptpmqfihquc
          xyt5k2ne5oqunwic5: xznk4uicnif7kv3zo
          xooylaev7pwuvqsu5: ${{ needs.xjln6vglt73ligtvk.outputs.xz7sxqj2lr6xr3cga }}
          xrazdeeqbo2k2kic6: ${{ needs.xjln6vglt73ligtvk.outputs.xrav2lcmeqo7drpuv }}
          xrelspbpgxl7ikj4t: ${{ needs.xjln6vglt73ligtvk.outputs.xxauzfp5l5zzj6o6s }}
          xk4m4466ajb5azjnz: ${{ secrets.x4amx5gk3bx3enrbj }}
          xcb3uc7rrykueqktt: ${{ secrets.xs32tk6e4q3upr5au }}
          x565azhqwteiksi2z: ${{ secrets.x72l2e5chadt2wgmr }}
          xqc3kqqftsenfeumg: ${{ secrets.xsemwodlffbmzobxv }}
          xvimkivhx2tqrmzp5: ${{ secrets.xj4q2oe24ul3gocs3 }}
          xmwtti62frqtunvpo: ${{ secrets.xvp3lwebscbhq4np4 }}
        run: ./.github/bin/xmxqxufh5bxnxdc4k
  xoniqgmq5ayjevygg:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xjln6vglt73ligtvk
      - x3r7ynpbgkydxit4f
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        x2vvirenbxgar2u7i: ${{ fromJSON(needs.x3r7ynpbgkydxit4f.outputs.xznk4uicnif7kv3zo) }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xeyta5i3nv4bkuler: ${{ secrets.xh7m2ldpw5cql5sep }}
          xqenmlrfq62oinaw4: ${{ secrets.xfwywr56poqftmwc3 }}
          xujyswu2qkj4iywg6: ${{ secrets.xi7t32r45js5lgbof }}
          xcgagul6y7tlo65ik: xv2otvniesitpoiep
          xyt5k2ne5oqunwic5: ''
          x2dietprkhuocmedb: ${{ needs.xjln6vglt73ligtvk.outputs.xh7ju4mc3kbj3h3ca }}
          x56hd5hs43cojcf2h: ${{ needs.xjln6vglt73ligtvk.outputs.xrav2lcmeqo7drpuv }}
          x5v7nwxwbtl3gfvnk: ${{ needs.xjln6vglt73ligtvk.outputs.xz7sxqj2lr6xr3cga }}
          xgvon4sjn5bfhm2fz: ${{ matrix.x2vvirenbxgar2u7i }}
          xmmmsj3hag63qll3h: ${{ needs.xjln6vglt73ligtvk.outputs.x3r74esd2t3qivujw }}
          xojekwsqwhu7ddmpo: ${{ needs.xjln6vglt73ligtvk.outputs.xxauzfp5l5zzj6o6s }}
          xk4m4466ajb5azjnz: ${{ secrets.x4amx5gk3bx3enrbj }}
          xcb3uc7rrykueqktt: ${{ secrets.xs32tk6e4q3upr5au }}
          xdmdxzpdp5pe3vftc: ${{ secrets.xoemgrge6ctvxrxk2 }}
          x565azhqwteiksi2z: ${{ secrets.x72l2e5chadt2wgmr }}
          xqc3kqqftsenfeumg: ${{ secrets.xsemwodlffbmzobxv }}
          xvimkivhx2tqrmzp5: ${{ secrets.xj4q2oe24ul3gocs3 }}
          x4sedoqq2evjtdjwo: ${{ secrets.xjou5uheia6hhfvie }}
          x2kslc3sbbqg6jlfx: ${{ secrets.xai2v37lja6necano }}
          xqj6xvz2zsg65uj27: ${{ secrets.xl7tiqgs7ughi7axq }}
          xmwtti62frqtunvpo: ${{ secrets.xvp3lwebscbhq4np4 }}
          x23ufwtu3w3m3of4s: ${{ secrets.xrmngwyo3hdqeiyib }}
          xtpfxqz5ncvup4nsx: ${{ secrets.x5lnbwhq3brjnrexb }}
          xw3amogoa3nru6zze: ${{ secrets.xkwcxkcwanvtl6yye }}
        run: ./.github/bin/xmxqxufh5bxnxdc4k
  xhkpazyh5vphz4e2s:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - xoniqgmq5ayjevygg
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          xeyta5i3nv4bkuler: ${{ secrets.xh7m2ldpw5cql5sep }}
          xqenmlrfq62oinaw4: ${{ secrets.xfwywr56poqftmwc3 }}
          xujyswu2qkj4iywg6: ${{ secrets.xi7t32r45js5lgbof }}
          xcgagul6y7tlo65ik: x7fslijnykq5ulvwp
          xyt5k2ne5oqunwic5: ''
          xnd55zqkpidzdipfl: ${{ needs.xoniqgmq5ayjevygg.result }}
          x565azhqwteiksi2z: ${{ secrets.x72l2e5chadt2wgmr }}
          xqc3kqqftsenfeumg: ${{ secrets.xsemwodlffbmzobxv }}
          xvimkivhx2tqrmzp5: ${{ secrets.xj4q2oe24ul3gocs3 }}
          xmwtti62frqtunvpo: ${{ secrets.xvp3lwebscbhq4np4 }}
        run: ./.github/bin/xmxqxufh5bxnxdc4k
